Repository lycoris62/sparta-movie-newsfeed, pull requests merged in 2023-11, with the labels that each got.

#2 Update README.md
  README.md
Labels: enhancement

#4 feat : add review domain
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewGetController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/ReviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/repository/ReviewRepository.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#7 Feat/add user model
  src/main/java/sparta/ifour/movietalk/MovietalkApplication.java
  src/main/java/sparta/ifour/movietalk/domain/model/BaseEntity.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserSignupRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/entity/User.java
  src/main/java/sparta/ifour/movietalk/domain/user/repository/UserRepository.java
Labels: enhancement

#10 Feat/add comment domain
  src/main/java/sparta/ifour/movietalk/domain/comment/controller/CommentController.java
  src/main/java/sparta/ifour/movietalk/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/comment/entity/Comment.java
  src/main/java/sparta/ifour/movietalk/domain/comment/repository/CommentRepository.java
  src/main/java/sparta/ifour/movietalk/domain/comment/service/CommentService.java
Labels: enhancement

#13 Feat/add review controller method
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewGetController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/ReviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#15 Feat/add review domain
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewCudController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/ReviewRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#17 Feat : 리뷰 검색 목록 조회
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewGetController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#19 Feat/create comment
  src/main/java/sparta/ifour/movietalk/domain/comment/controller/CommentController.java
  src/main/java/sparta/ifour/movietalk/domain/comment/dto/response/CommentCreateResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/comment/entity/Comment.java
  src/main/java/sparta/ifour/movietalk/domain/comment/service/CommentService.java
Labels: enhancement

#21 Feat/update comment
  src/main/java/sparta/ifour/movietalk/domain/comment/controller/CommentController.java
  src/main/java/sparta/ifour/movietalk/domain/comment/dto/request/CommentUpdateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/comment/entity/Comment.java
  src/main/java/sparta/ifour/movietalk/domain/comment/service/CommentService.java
Labels: enhancement

#20 Feat/create review
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewGetController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/request/ReviewRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/response/ReviewDetailResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/response/ReviewPreviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/response/ReviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#22 Feat/add user api
  src/main/java/sparta/ifour/movietalk/domain/user/controller/AuthController.java
  src/main/java/sparta/ifour/movietalk/domain/user/controller/UserController.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserLoginRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserPasswordUpdateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserProfileUpdateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/response/UserProfileResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/entity/User.java
  src/main/java/sparta/ifour/movietalk/domain/user/repository/UserRepository.java
  src/main/java/sparta/ifour/movietalk/domain/user/service/AuthService.java
  src/main/java/sparta/ifour/movietalk/domain/user/service/UserService.java
Labels: enhancement

#24 Feat/delete comment
  src/main/java/sparta/ifour/movietalk/domain/comment/controller/CommentController.java
  src/main/java/sparta/ifour/movietalk/domain/comment/service/CommentService.java
Labels: enhancement

#27 Feat/add entity hashtag
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewQueryController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Hashtag.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/ReviewHashtag.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/repository/HashtagRepository.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/repository/ReviewHashTagRepository.java
Labels: enhancement

#26 Feat/update review
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#28 Feat/delete review
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#32 Feat/add like entity
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Like.java
Labels: enhancement

#30 Feat : 특정 해시태그가 포함된 리뷰 조회 메서드 추가
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewQueryController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/repository/HashtagRepository.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#36 Feat/add like func
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Like.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/repository/LikeRepository.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#43 Fix/get login token
  src/main/java/sparta/ifour/movietalk/domain/user/controller/AuthController.java
  src/main/java/sparta/ifour/movietalk/domain/user/entity/User.java
  src/main/java/sparta/ifour/movietalk/domain/user/service/AuthService.java
  src/main/java/sparta/ifour/movietalk/global/config/security/UserDetailsImpl.java
  src/main/java/sparta/ifour/movietalk/global/config/security/UserDetailsServiceImpl.java
Labels: bug

#42 Fix/comment api edit
  src/main/java/sparta/ifour/movietalk/domain/comment/controller/CommentController.java
  src/main/java/sparta/ifour/movietalk/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/comment/service/CommentService.java
Labels: enhancement

#37 Feat/ Response Dto 변경 및 Controller&Service 메서드 반환타입 변경
  src/main/java/sparta/ifour/movietalk/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewQueryController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/response/ReviewDetailResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/response/ReviewPreviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/dto/response/ReviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#44 Feat/add verify user
  src/main/java/sparta/ifour/movietalk/domain/reviews/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/reviews/service/ReviewService.java
Labels: enhancement

#45 Feat/add user edit api
  src/main/java/sparta/ifour/movietalk/domain/user/controller/UserController.java
  src/main/java/sparta/ifour/movietalk/domain/user/service/AuthService.java
  src/main/java/sparta/ifour/movietalk/domain/user/service/UserService.java
  src/main/java/sparta/ifour/movietalk/global/config/security/UserDetailsImpl.java
  src/main/java/sparta/ifour/movietalk/global/config/security/WebSecurityConfig.java
Labels: enhancement

#47 Fix/edit profile api
  src/main/java/sparta/ifour/movietalk/domain/user/controller/UserController.java
  src/main/java/sparta/ifour/movietalk/domain/user/repository/UserRepository.java
  src/main/java/sparta/ifour/movietalk/domain/user/service/UserService.java
  src/main/java/sparta/ifour/movietalk/global/config/security/jwt/JwtFilter.java
Labels: bug

#48 Fix/like add delete
  src/main/java/sparta/ifour/movietalk/domain/comment/entity/Comment.java
  src/main/java/sparta/ifour/movietalk/domain/comment/service/CommentService.java
  src/main/java/sparta/ifour/movietalk/domain/review/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/review/controller/ReviewQueryController.java
  src/main/java/sparta/ifour/movietalk/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/dto/response/ReviewPreviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/entity/Hashtag.java
  src/main/java/sparta/ifour/movietalk/domain/review/entity/Like.java
  src/main/java/sparta/ifour/movietalk/domain/review/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/review/entity/ReviewHashtag.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/HashtagRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/LikeRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/ReviewHashTagRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/ReviewRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewService.java
Labels: bug

#50 fix : 댓글 엔티티 연관관계 nullable false로 수정
  src/main/java/sparta/ifour/movietalk/domain/comment/entity/Comment.java
Labels: bug

#51 fix : 리뷰커맨드 컨트롤러에서 좋아요 관련 method patch로 변경
  src/main/java/sparta/ifour/movietalk/domain/review/controller/ReviewCommandController.java
Labels: enhancement

#49 Feat/add query sort
  src/main/java/sparta/ifour/movietalk/domain/review/controller/ReviewQueryController.java
  src/main/java/sparta/ifour/movietalk/domain/review/enums/ReviewSort.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/ReviewRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewService.java
Labels: enhancement

#54 Feat/exception handle
  src/main/java/sparta/ifour/movietalk/global/error/ErrorCode.java
  src/main/java/sparta/ifour/movietalk/global/error/ErrorResponse.java
  src/main/java/sparta/ifour/movietalk/global/error/GlobalExceptionHandler.java
  src/main/java/sparta/ifour/movietalk/global/exception/InvalidAccessException.java
  src/main/java/sparta/ifour/movietalk/global/exception/NotFoundException.java
Labels: enhancement

#56 Feat/add tag DB
  src/main/java/sparta/ifour/movietalk/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/HashtagRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewService.java
Labels: enhancement

#55 Fix/edit reviews get api
  src/main/java/sparta/ifour/movietalk/domain/review/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/review/controller/ReviewQueryController.java
  src/main/java/sparta/ifour/movietalk/domain/review/enums/ReviewSort.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/LikeRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/repository/ReviewRepository.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewCommandService.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewQueryService.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewService.java
Labels: enhancement

#57 Feat/exception handle
  src/main/java/sparta/ifour/movietalk/domain/comment/service/CommentService.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewCommandService.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewQueryService.java
  src/main/java/sparta/ifour/movietalk/global/error/GlobalExceptionHandler.java
Labels: enhancement

#59 Fix/validation edit
  src/main/java/sparta/ifour/movietalk/domain/comment/controller/CommentController.java
  src/main/java/sparta/ifour/movietalk/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/comment/dto/request/CommentUpdateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/controller/ReviewCommandController.java
  src/main/java/sparta/ifour/movietalk/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserLoginRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserPasswordUpdateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserProfileUpdateRequestDto.java
  src/main/java/sparta/ifour/movietalk/domain/user/dto/request/UserSignupRequestDto.java
Labels: enhancement

#60 Fix/use review exception
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewCommandService.java
  src/main/java/sparta/ifour/movietalk/domain/user/service/AuthService.java
Labels: enhancement

#61 Fix/review tag
  src/main/java/sparta/ifour/movietalk/domain/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/dto/response/ReviewPreviewResponseDto.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewCommandService.java
Labels: enhancement

#62 fix : 태그로 검색히 조회기능 filtering 코드 수정
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewQueryService.java
Labels: bug

#64 Fix/add review tag
  src/main/java/sparta/ifour/movietalk/domain/review/entity/Hashtag.java
  src/main/java/sparta/ifour/movietalk/domain/review/entity/Review.java
  src/main/java/sparta/ifour/movietalk/domain/review/service/ReviewCommandService.java
Labels: bug

#65 Update README.md
  README.md
Labels: enhancement

#66 Update README.md
  README.md
Labels: documentation
